CREATE DATABASE IF NOT EXISTS mybibli CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mybibli;

CREATE TABLE IF NOT EXISTS livros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    autor VARCHAR(150) NOT NULL,
    genero VARCHAR(100) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL,
    nota TINYINT NULL
);

